from .stores.products_store import ProductOverThousand
from .stores.products_under_thousand import ProductUnderThousand
from .orders.completed_orders import CompletedOrders
from .orders.incomplete_orders import IncompletedOrders
from .customers.customer_favorite_stores import CustomerFavorites